package main

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/pflag"
	"github.com/spf13/viper"
)

// showVersion 标记是否只输出版本信息后退出。
// showVersion marks whether the process should print version information and exit.
var showVersion bool

// validLogLevels 保存配置允许的日志级别。
// validLogLevels stores the log levels accepted by configuration.
var validLogLevels = map[string]struct{}{
	"debug": {},
	"info":  {},
	"warn":  {},
	"error": {},
}

const (
	// signProviderLocal 表示使用本地 JS 签名。
	// signProviderLocal means signatures are generated locally with JavaScript.
	signProviderLocal = "local"
	// signProviderTikHub 表示使用 TikHub 在线签名。
	// signProviderTikHub means signatures are generated by TikHub's online API.
	signProviderTikHub = "tikhub"
)

// CookieConfig 保存默认 Cookie 和按房间覆盖的 Cookie。
// CookieConfig stores the default cookie and per-room cookie overrides.
type CookieConfig struct {
	Douyin string            // 抖音默认 Cookie。 Default Douyin Cookie.
	Rooms  map[string]string // 按直播间 ID 配置的 Cookie。 Per-room Cookie overrides keyed by room ID.
}

// MonitorConfig 保存未开播轮询和通知间隔配置。
// MonitorConfig stores polling and notification intervals for offline-room monitoring.
type MonitorConfig struct {
	PollInterval   time.Duration
	NotifyInterval time.Duration
}

// LogConfig 保存日志配置。
// LogConfig stores logging configuration.
type LogConfig struct {
	Level string
}

// SignConfig stores WebSocket signature provider configuration.
type SignConfig struct {
	Provider string
}

// TikHubConfig stores TikHub API configuration.
type TikHubConfig struct {
	Key string
}

// Config 保存应用运行所需的全部配置。
// Config stores all runtime configuration for the application.
type Config struct {
	Port    string
	Unknown bool
	Cookie  CookieConfig
	Monitor MonitorConfig
	Log     LogConfig
	Sign    SignConfig
	TikHub  TikHubConfig
}

// firstNonEmpty 返回第一个去空白后非空的字符串。
// firstNonEmpty returns the first non-empty string after trimming spaces.
// 参数/Parameters:
//   - values: 候选字符串列表。 Candidate strings.
func firstNonEmpty(values ...string) string {
	for _, v := range values {
		if strings.TrimSpace(v) != "" {
			return strings.TrimSpace(v)
		}
	}
	return ""
}

// normalizeSignProvider 规范化签名来源配置并校验合法性。
// normalizeSignProvider normalizes and validates the configured signature provider.
// 参数/Parameters:
//   - provider: 配置或命令行传入的签名来源名称。 Sign provider name from config or CLI.
func normalizeSignProvider(provider string) (string, error) {
	provider = strings.ToLower(strings.TrimSpace(provider))
	if provider == "" {
		provider = defaultSignProvider
	}

	switch provider {
	case "local", "js", "javascript":
		return signProviderLocal, nil
	case "tikhub", "tik-hub", "tik_hub":
		return signProviderTikHub, nil
	default:
		return "", fmt.Errorf("sign.provider 配置无效: %s，可选值: local, tikhub", provider)
	}
}

// NewConfig 读取命令行、环境变量和配置文件并生成应用配置。
// NewConfig reads flags, environment variables, and config files into application configuration.
func NewConfig() (*Config, error) {
	// 绑定命令行参数。
	// Bind command-line flags.
	pflag.String("port", "1088", "WebSocket 服务端口")
	pflag.Bool("unknown", false, "是否输出未知源的 pb 消息")
	pflag.String("log-level", "info", "日志级别: debug, info, warn, error")
	pflag.String("sign-provider", defaultSignProvider, "WebSocket 签名来源: local, tikhub")
	pflag.String("tikhub-key", "", "TikHub API Key，用于在线生成 WebSocket xb 签名")
	configFile := pflag.String("config", "", "指定配置文件路径")
	pflag.BoolVar(&showVersion, "version", false, "输出版本信息")
	pflag.Parse()
	if showVersion {
		fmt.Println(VersionString())
		os.Exit(0)
	}

	// 绑定到 viper。
	// Bind flags to viper.
	if err := viper.BindPFlags(pflag.CommandLine); err != nil {
		return nil, err
	}

	// 配置文件设置。
	// Configure config file lookup.
	if *configFile != "" {
		viper.SetConfigFile(*configFile)
	} else {
		viper.SetConfigName("config")
		viper.SetConfigType("yaml")

		// 优先从可执行文件所在目录读取配置，避免双击启动时找不到 config.yaml。
		// Prefer the executable directory so double-click startup can find config.yaml.
		exePath, err := os.Executable()
		if err == nil {
			exeDir := filepath.Dir(exePath)
			viper.AddConfigPath(exeDir)
		}

		viper.AddConfigPath(".")
		viper.AddConfigPath("$HOME/.app")
		viper.AddConfigPath("/etc/app/")
	}

	// 环境变量支持。
	// Enable environment variable support.
	viper.SetEnvPrefix("APP")
	viper.AutomaticEnv()
	viper.SetEnvKeyReplacer(strings.NewReplacer(".", "_", "-", "_"))

	// 设置默认值。
	// Set defaults.
	viper.SetDefault("port", "1088")
	viper.SetDefault("unknown", false)
	viper.SetDefault("cookie.douyin", "")
	viper.SetDefault("cookie.rooms", map[string]string{})
	viper.SetDefault("monitor.poll_interval", "15s")
	viper.SetDefault("monitor.notify_interval", "30s")
	viper.SetDefault("log.level", "info")
	viper.SetDefault("sign.provider", defaultSignProvider)
	viper.SetDefault("tikhub.key", "")
	// 读取配置。
	// Read configuration.
	if err := viper.ReadInConfig(); err != nil {
		var configFileNotFoundError viper.ConfigFileNotFoundError
		if !errors.As(err, &configFileNotFoundError) {
			return nil, fmt.Errorf("读取配置文件失败：%w", err)
		}
		// 配置文件不存在时给出提示。
		// Print a hint when the config file does not exist.
		fmt.Println("⚠️  配置文件未找到，使用默认值或命令行参数")
		fmt.Println("💡 建议在同目录下创建 config.yaml 文件")
	} else {
		fmt.Printf("✅ 使用配置文件：%s\n", viper.ConfigFileUsed())
	}

	pollInterval, err := time.ParseDuration(viper.GetString("monitor.poll_interval"))
	if err != nil {
		return nil, fmt.Errorf("monitor.poll_interval 配置无效：%w", err)
	}
	if pollInterval <= 0 {
		return nil, fmt.Errorf("monitor.poll_interval 必须大于 0")
	}

	notifyInterval, err := time.ParseDuration(viper.GetString("monitor.notify_interval"))
	if err != nil {
		return nil, fmt.Errorf("monitor.notify_interval 配置无效：%w", err)
	}
	if notifyInterval <= 0 {
		return nil, fmt.Errorf("monitor.notify_interval 必须大于 0")
	}

	logLevel := viper.GetString("log.level")
	if flag := pflag.Lookup("log-level"); flag != nil && flag.Changed {
		logLevel = flag.Value.String()
	}
	logLevel = strings.ToLower(firstNonEmpty(logLevel, "info"))
	if _, ok := validLogLevels[logLevel]; !ok {
		return nil, fmt.Errorf("log.level 配置无效: %s", logLevel)
	}

	signProvider := viper.GetString("sign.provider")
	if flag := pflag.Lookup("sign-provider"); flag != nil && flag.Changed {
		signProvider = flag.Value.String()
	}
	signProvider, err = normalizeSignProvider(signProvider)
	if err != nil {
		return nil, err
	}

	tikHubKey := viper.GetString("tikhub.key")
	if flag := pflag.Lookup("tikhub-key"); flag != nil && flag.Changed {
		tikHubKey = flag.Value.String()
	}

	// 填充 Config 结构体。
	// Populate the Config struct.
	cfg := &Config{
		Port:    viper.GetString("port"),
		Unknown: viper.GetBool("unknown"),
		Cookie: CookieConfig{
			Douyin: viper.GetString("cookie.douyin"),
			Rooms:  viper.GetStringMapString("cookie.rooms"),
		},
		Monitor: MonitorConfig{
			PollInterval:   pollInterval,
			NotifyInterval: notifyInterval,
		},
		Log: LogConfig{
			Level: logLevel,
		},
		Sign: SignConfig{
			Provider: signProvider,
		},
		TikHub: TikHubConfig{
			Key: strings.TrimSpace(tikHubKey),
		},
	}

	return cfg, nil
}
