package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"
	"unicode"

	douyinLive "github.com/jwwsjlm/douyinLive/v2"
	"github.com/spf13/pflag"
	"github.com/spf13/viper"
	"gopkg.in/yaml.v3"
)

// ErrVersionRequested tells the CLI layer that only version output was requested.
// ErrVersionRequested 表示调用者只请求输出版本信息。
var ErrVersionRequested = errors.New("version requested")

// validLogLevels 保存配置允许的日志级别。
// validLogLevels stores the log levels accepted by configuration.
var validLogLevels = map[string]struct{}{
	"debug": {},
	"info":  {},
	"warn":  {},
	"error": {},
}

const (
	// signProviderLocal 表示优先使用本地原生 Go 签名。
	// signProviderLocal means signatures use the native local Go implementation first.
	signProviderLocal = "local"
	// signProviderTikHub 表示使用 TikHub 在线签名。
	// signProviderTikHub means signatures are generated by TikHub's online API.
	signProviderTikHub = "tikhub"
)

// CookieConfig 保存默认 Cookie 和按房间覆盖的 Cookie。
// CookieConfig stores the default cookie and per-room cookie overrides.
type CookieConfig struct {
	UseStored bool // 是否使用配置文件中的预存 Cookie。 Whether to use preconfigured cookies.
	// useStoredSet distinguishes a programmatic zero-value Config from an
	// explicit opt-out. YAML/env loading always sets it; code embedding the
	// service can call SetUseStoredCookie when it needs to disable cookies.
	// useStoredSet 区分程序化零值 Config 与显式关闭；YAML/env 加载总会设置它，
	// 嵌入服务的代码可调用 SetUseStoredCookie 明确关闭 Cookie。
	useStoredSet bool
	Douyin       string            // 抖音默认 Cookie。 Default Douyin Cookie.
	Rooms        map[string]string // 按直播间 ID 配置的 Cookie。 Per-room Cookie overrides keyed by room ID.
}

// SetUseStoredCookie explicitly selects whether this programmatic service
// configuration may use the configured global and room-level cookies.
// SetUseStoredCookie 为程序化服务配置显式选择是否使用全局和按房间预存 Cookie。
func (c *CookieConfig) SetUseStoredCookie(enabled bool) {
	if c == nil {
		return
	}
	c.UseStored = enabled
	c.useStoredSet = true
}

// MonitorConfig 保存未开播轮询和通知间隔配置。
// MonitorConfig stores polling and notification intervals for offline-room monitoring.
type MonitorConfig struct {
	PollInterval   time.Duration
	NotifyInterval time.Duration
}

// LogConfig 保存日志配置。
// LogConfig stores logging configuration.
type LogConfig struct {
	Level string
}

// SignConfig stores WebSocket signature provider configuration.
type SignConfig struct {
	Provider string
}

// TikHubConfig stores TikHub API configuration.
type TikHubConfig struct {
	Key string
}

// APIConfig stores optional read-only HTTP API authentication settings.
// APIConfig 保存可选的只读 HTTP API 认证配置。
type APIConfig struct {
	Key            string
	AllowedDomains []string
}

// WebSocketConfig stores the configurable local WebSocket route.
// WebSocketConfig 保存可自定义的本地 WebSocket 路由。
type WebSocketConfig struct {
	Path           string
	AllowedOrigins []string
}

// configFileSchema is used only for strict YAML key validation. Runtime value
// precedence remains owned by Viper so existing flag and environment behavior
// is preserved.
// configFileSchema 仅用于严格校验 YAML 字段；运行时优先级仍由 Viper 处理，
// 因此不会改变已有的命令行和环境变量覆盖规则。
type configFileSchema struct {
	Port      string                    `yaml:"port"`
	Unknown   bool                      `yaml:"unknown"`
	Log       configFileLogSchema       `yaml:"log"`
	Sign      configFileSignSchema      `yaml:"sign"`
	TikHub    configFileTikHubSchema    `yaml:"tikhub"`
	API       configFileAPISchema       `yaml:"api"`
	WebSocket configFileWebSocketSchema `yaml:"websocket"`
	Monitor   configFileMonitorSchema   `yaml:"monitor"`
	Cookie    configFileCookieSchema    `yaml:"cookie"`
}

type configFileLogSchema struct {
	Level string `yaml:"level"`
}

type configFileSignSchema struct {
	Provider string `yaml:"provider"`
}

type configFileTikHubSchema struct {
	Key string `yaml:"key"`
}

type configFileAPISchema struct {
	Key            string   `yaml:"key"`
	AllowedDomains []string `yaml:"allowed_domains"`
}

type configFileWebSocketSchema struct {
	Path           string   `yaml:"path"`
	AllowedOrigins []string `yaml:"allowed_origins"`
}

type configFileMonitorSchema struct {
	PollInterval   string `yaml:"poll_interval"`
	NotifyInterval string `yaml:"notify_interval"`
}

type configFileCookieSchema struct {
	UseStored bool              `yaml:"use_stored"`
	Douyin    string            `yaml:"douyin"`
	Rooms     map[string]string `yaml:"rooms"`
}

func loadConfigFileSchema(path string) (configFileSchema, error) {
	var schema configFileSchema
	file, err := os.Open(path)
	if err != nil {
		return schema, err
	}
	defer file.Close()

	decoder := yaml.NewDecoder(file)
	decoder.KnownFields(true)
	if err := decoder.Decode(&schema); err != nil {
		return schema, err
	}
	var extra interface{}
	if err := decoder.Decode(&extra); !errors.Is(err, io.EOF) {
		if err == nil {
			return schema, errors.New("配置文件只能包含一个 YAML 文档")
		}
		return schema, err
	}
	return schema, nil
}

// configStringSlice reads a list-valued setting while giving environment
// variables an explicit, deployment-friendly representation. Viper splits a
// raw environment string only on whitespace; accepting comma-separated and
// JSON-array forms avoids silently treating multiple domains as one value.
// configStringSlice 读取列表配置，并让环境变量明确支持逗号、空白或 JSON 数组格式。
func configStringSlice(v *viper.Viper, key, envName string) ([]string, error) {
	if raw, ok := os.LookupEnv(envName); ok {
		raw = strings.TrimSpace(raw)
		if raw == "" {
			return nil, nil
		}
		if strings.HasPrefix(raw, "[") {
			var values []string
			if err := json.Unmarshal([]byte(raw), &values); err != nil {
				return nil, fmt.Errorf("%s 必须是字符串数组、逗号分隔或空白分隔列表: %w", envName, err)
			}
			return values, nil
		}
		return strings.FieldsFunc(raw, func(r rune) bool {
			return r == ',' || unicode.IsSpace(r)
		}), nil
	}
	return v.GetStringSlice(key), nil
}

// configRoomCookies preserves case-sensitive room IDs from YAML while keeping
// the documented environment-over-file precedence. APP_COOKIE_ROOMS uses a
// JSON object so Cookie values containing commas, semicolons, or spaces remain
// unambiguous.
// configRoomCookies 在保留 YAML 房间号大小写的同时维持环境变量优先级；
// APP_COOKIE_ROOMS 使用 JSON 对象，避免 Cookie 中的逗号、分号或空格产生歧义。
func configRoomCookies(v *viper.Viper, fileSchema configFileSchema, configFileLoaded bool) (map[string]string, error) {
	if raw, ok := os.LookupEnv("APP_COOKIE_ROOMS"); ok {
		raw = strings.TrimSpace(raw)
		if raw == "" {
			return map[string]string{}, nil
		}
		var values map[string]string
		if err := json.Unmarshal([]byte(raw), &values); err != nil {
			return nil, fmt.Errorf("APP_COOKIE_ROOMS 必须是 JSON 字符串对象: %w", err)
		}
		if values == nil {
			return map[string]string{}, nil
		}
		return values, nil
	}
	if configFileLoaded && fileSchema.Cookie.Rooms != nil {
		return fileSchema.Cookie.Rooms, nil
	}
	return v.GetStringMapString("cookie.rooms"), nil
}

// normalizeAllowedOrigins normalizes optional browser Origin allowlist entries.
// normalizeAllowedOrigins 规范化可选的浏览器 Origin 白名单。
func normalizeAllowedOrigins(values []string) ([]string, error) {
	seen := make(map[string]struct{}, len(values))
	result := make([]string, 0, len(values))
	for index, raw := range values {
		value := strings.TrimSpace(raw)
		if value == "" {
			continue
		}
		if value == "*" {
			return nil, fmt.Errorf("websocket.allowed_origins[%d] 不支持通配符 *；留空表示允许所有来源", index)
		}
		u, err := url.Parse(value)
		if err != nil || u.Scheme == "" || u.Host == "" || u.User != nil || u.Path != "" || u.RawQuery != "" || u.Fragment != "" || u.Opaque != "" {
			return nil, fmt.Errorf("websocket.allowed_origins[%d] 配置无效: %q", index, raw)
		}
		scheme := strings.ToLower(u.Scheme)
		if scheme != "http" && scheme != "https" {
			return nil, fmt.Errorf("websocket.allowed_origins[%d] 仅支持 http/https Origin: %q", index, raw)
		}
		origin := scheme + "://" + strings.ToLower(u.Host)
		if _, ok := seen[origin]; ok {
			continue
		}
		seen[origin] = struct{}{}
		result = append(result, origin)
	}
	return result, nil
}

// Config 保存应用运行所需的全部配置。
// Config stores all runtime configuration for the application.
type Config struct {
	Port      string
	Unknown   bool
	Cookie    CookieConfig
	Monitor   MonitorConfig
	Log       LogConfig
	Sign      SignConfig
	TikHub    TikHubConfig
	API       APIConfig
	WebSocket WebSocketConfig
}

// firstNonEmpty 返回第一个去空白后非空的字符串。
// firstNonEmpty returns the first non-empty string after trimming spaces.
// 参数/Parameters:
//   - values: 候选字符串列表。 Candidate strings.
func firstNonEmpty(values ...string) string {
	for _, v := range values {
		if strings.TrimSpace(v) != "" {
			return strings.TrimSpace(v)
		}
	}
	return ""
}

// normalizeAllowedDomains normalizes configured URL host suffixes.
// normalizeAllowedDomains 规范化 URL 域名白名单。
func normalizeAllowedDomains(values []string) ([]string, error) {
	seen := make(map[string]struct{}, len(values))
	result := make([]string, 0, len(values))
	for index, value := range values {
		domain := strings.ToLower(strings.TrimSpace(value))
		domain = strings.TrimPrefix(domain, ".")
		domain = strings.TrimSuffix(domain, ".")
		if domain == "" {
			continue
		}
		if strings.ContainsAny(domain, "/?#\\\\@ :,\t\r\n") || strings.Contains(domain, "..") {
			return nil, fmt.Errorf("api.allowed_domains[%d] 配置无效: %q", index, value)
		}
		if domain != "douyin.com" && !strings.HasSuffix(domain, ".douyin.com") {
			return nil, fmt.Errorf("api.allowed_domains[%d] 只允许 douyin.com 及其子域名: %q", index, value)
		}
		if _, ok := seen[domain]; ok {
			continue
		}
		seen[domain] = struct{}{}
		result = append(result, domain)
	}
	if len(result) == 0 {
		return []string{"douyin.com"}, nil
	}
	return result, nil
}

func normalizeWebSocketPath(value string) (string, error) {
	path := strings.TrimSpace(value)
	if path == "" {
		path = "/ws"
	}
	if !strings.HasPrefix(path, "/") {
		path = "/" + path
	}
	path = strings.TrimRight(path, "/")
	if path == "" {
		return "", errors.New("websocket.path 不能为根路径")
	}
	// net/http ServeMux treats braces as wildcard syntax and unescapes percent
	// encoded path segments before checking pattern conflicts. The WebSocket
	// route is configuration, not a ServeMux pattern, so keep it strictly
	// literal and reject both forms instead of allowing a startup panic or a
	// collision hidden behind an encoded path.
	// net/http ServeMux 会把花括号解释为通配符，并在检查路由冲突前解码
	// 百分号路径。WebSocket 路由是字面配置，不是 ServeMux pattern，因此
	// 直接拒绝这两类语法，避免启动 panic 或编码后的保留路由冲突。
	if strings.ContainsAny(path, "?#\\\t\r\n %{}") || strings.Contains(path, "//") || strings.Contains(path, "..") {
		return "", fmt.Errorf("websocket.path 配置无效: %q", value)
	}
	if path == "/health" || path == "/metrics" || path == "/api" || strings.HasPrefix(path, "/api/") {
		return "", fmt.Errorf("websocket.path 与保留 HTTP 路由冲突: %q", path)
	}
	return path, nil
}

// normalizeSignProvider 规范化签名来源配置并校验合法性。
// normalizeSignProvider normalizes and validates the configured signature provider.
// 参数/Parameters:
//   - provider: 配置或命令行传入的签名来源名称。 Sign provider name from config or CLI.
func normalizeSignProvider(provider string) (string, error) {
	provider = strings.ToLower(strings.TrimSpace(provider))
	if provider == "" {
		provider = defaultSignProvider
	}

	switch provider {
	case "local", "js", "javascript":
		return signProviderLocal, nil
	case "tikhub", "tik-hub", "tik_hub":
		return signProviderTikHub, nil
	default:
		return "", fmt.Errorf("sign.provider 配置无效: %s，可选值: local, tikhub", provider)
	}
}

// NewConfig 读取命令行、环境变量和配置文件并生成应用配置。
// NewConfig reads flags, environment variables, and config files into application configuration.
func NewConfig() (*Config, error) {
	// Use per-call flag and Viper instances so tests and embedders can load
	// configuration repeatedly without mutating process-global state.
	flags := pflag.NewFlagSet("douyinLive", pflag.ContinueOnError)
	flags.SetOutput(os.Stderr)
	portFlag := flags.String("port", "1088", "WebSocket 服务端口")
	flags.Bool("unknown", false, "是否输出未知源的 pb 消息")
	logLevelFlag := flags.String("log-level", "info", "日志级别: debug, info, warn, error")
	signProviderFlag := flags.String("sign-provider", defaultSignProvider, "WebSocket 签名来源: local, tikhub")
	tikHubKeyFlag := flags.String("tikhub-key", "", "TikHub API Key，用于在线生成 WebSocket 签名")
	configFileFlag := flags.String("config", "", "指定配置文件路径")
	versionFlag := flags.Bool("version", false, "输出版本信息")
	if err := flags.Parse(os.Args[1:]); err != nil {
		return nil, err
	}
	if *versionFlag {
		return nil, ErrVersionRequested
	}

	v := viper.New()
	if err := v.BindPFlags(flags); err != nil {
		return nil, err
	}

	if *configFileFlag != "" {
		v.SetConfigFile(*configFileFlag)
	} else {
		v.SetConfigName("config")
		v.SetConfigType("yaml")
		if exePath, err := os.Executable(); err == nil {
			v.AddConfigPath(filepath.Dir(exePath))
		}
		v.AddConfigPath(".")
		v.AddConfigPath("$HOME/.app")
		v.AddConfigPath("/etc/app/")
	}

	v.SetEnvPrefix("APP")
	v.AutomaticEnv()
	v.SetEnvKeyReplacer(strings.NewReplacer(".", "_", "-", "_"))
	v.SetDefault("port", "1088")
	v.SetDefault("unknown", false)
	v.SetDefault("cookie.douyin", "")
	v.SetDefault("cookie.rooms", map[string]string{})
	v.SetDefault("cookie.use_stored", true)
	v.SetDefault("monitor.poll_interval", "15s")
	v.SetDefault("monitor.notify_interval", "30s")
	v.SetDefault("log.level", "info")
	v.SetDefault("sign.provider", defaultSignProvider)
	v.SetDefault("tikhub.key", "")
	v.SetDefault("api.key", "")
	v.SetDefault("api.allowed_domains", []string{"douyin.com"})
	v.SetDefault("websocket.path", "/ws")
	v.SetDefault("websocket.allowed_origins", []string{})

	var fileSchema configFileSchema
	configFileLoaded := false
	if err := v.ReadInConfig(); err != nil {
		var configFileNotFoundError viper.ConfigFileNotFoundError
		if !errors.As(err, &configFileNotFoundError) {
			return nil, fmt.Errorf("读取配置文件失败：%w", err)
		}
		fmt.Println("⚠️  配置文件未找到，使用默认值或命令行参数")
		fmt.Println("💡 建议在同目录下创建 config.yaml 文件")
	} else {
		var err error
		fileSchema, err = loadConfigFileSchema(v.ConfigFileUsed())
		if err != nil {
			return nil, fmt.Errorf("配置文件字段校验失败：%w", err)
		}
		configFileLoaded = true
		fmt.Printf("✅ 使用配置文件：%s\n", v.ConfigFileUsed())
	}

	pollInterval, err := time.ParseDuration(v.GetString("monitor.poll_interval"))
	if err != nil {
		return nil, fmt.Errorf("monitor.poll_interval 配置无效：%w", err)
	}
	if pollInterval <= 0 {
		return nil, fmt.Errorf("monitor.poll_interval 必须大于 0")
	}

	notifyInterval, err := time.ParseDuration(v.GetString("monitor.notify_interval"))
	if err != nil {
		return nil, fmt.Errorf("monitor.notify_interval 配置无效：%w", err)
	}
	if notifyInterval <= 0 {
		return nil, fmt.Errorf("monitor.notify_interval 必须大于 0")
	}

	logLevel := v.GetString("log.level")
	if flags.Changed("log-level") {
		logLevel = *logLevelFlag
	}
	logLevel = strings.ToLower(firstNonEmpty(logLevel, "info"))
	if _, ok := validLogLevels[logLevel]; !ok {
		return nil, fmt.Errorf("log.level 配置无效: %s", logLevel)
	}

	signProvider := v.GetString("sign.provider")
	if flags.Changed("sign-provider") {
		signProvider = *signProviderFlag
	}
	signProvider, err = normalizeSignProvider(signProvider)
	if err != nil {
		return nil, err
	}

	tikHubKey := v.GetString("tikhub.key")
	if flags.Changed("tikhub-key") {
		tikHubKey = *tikHubKeyFlag
	}
	tikHubKey = strings.TrimSpace(tikHubKey)
	if signProvider == signProviderTikHub && tikHubKey == "" {
		return nil, errors.New("sign.provider=tikhub 时必须配置 tikhub.key、APP_TIKHUB_KEY 或 --tikhub-key")
	}

	port := v.GetString("port")
	if flags.Changed("port") {
		port = *portFlag
	}
	if _, err := parseConfiguredPort(port); err != nil {
		return nil, err
	}
	websocketPath, err := normalizeWebSocketPath(v.GetString("websocket.path"))
	if err != nil {
		return nil, err
	}
	allowedOriginValues, err := configStringSlice(v, "websocket.allowed_origins", "APP_WEBSOCKET_ALLOWED_ORIGINS")
	if err != nil {
		return nil, err
	}
	allowedOrigins, err := normalizeAllowedOrigins(allowedOriginValues)
	if err != nil {
		return nil, err
	}
	allowedDomainValues, err := configStringSlice(v, "api.allowed_domains", "APP_API_ALLOWED_DOMAINS")
	if err != nil {
		return nil, err
	}
	allowedDomains, err := normalizeAllowedDomains(allowedDomainValues)
	if err != nil {
		return nil, err
	}
	douyinCookie := strings.TrimSpace(v.GetString("cookie.douyin"))
	if err := validateCookieOverride(douyinCookie); err != nil {
		return nil, fmt.Errorf("cookie.douyin 配置无效: %w", err)
	}
	roomCookies, err := configRoomCookies(v, fileSchema, configFileLoaded)
	if err != nil {
		return nil, err
	}
	normalizedRoomCookies := make(map[string]string, len(roomCookies))
	for roomID, rawCookie := range roomCookies {
		roomID = strings.TrimSpace(roomID)
		if _, err := douyinLive.ValidateLiveID(roomID); err != nil {
			return nil, fmt.Errorf("cookie.rooms 中包含无效直播间标识: %q", roomID)
		}
		cookie := strings.TrimSpace(rawCookie)
		if err := validateCookieOverride(cookie); err != nil {
			return nil, fmt.Errorf("cookie.rooms[%q] 配置无效: %w", roomID, err)
		}
		normalizedRoomCookies[roomID] = cookie
	}

	// 填充 Config 结构体。
	// Populate the Config struct.
	cfg := &Config{
		Port:    port,
		Unknown: v.GetBool("unknown"),
		Cookie: CookieConfig{
			UseStored:    v.GetBool("cookie.use_stored"),
			useStoredSet: true,
			Douyin:       douyinCookie,
			Rooms:        normalizedRoomCookies,
		},
		Monitor: MonitorConfig{
			PollInterval:   pollInterval,
			NotifyInterval: notifyInterval,
		},
		Log: LogConfig{
			Level: logLevel,
		},
		Sign: SignConfig{
			Provider: signProvider,
		},
		TikHub: TikHubConfig{
			Key: tikHubKey,
		},
		API: APIConfig{
			Key:            strings.TrimSpace(v.GetString("api.key")),
			AllowedDomains: allowedDomains,
		},
		WebSocket: WebSocketConfig{Path: websocketPath, AllowedOrigins: allowedOrigins},
	}

	return cfg, nil
}
