package douyinLive

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	tikhub "github.com/jwwsjlm/Tikhub"
	"github.com/jwwsjlm/douyinLive/v2/jsScript"
)

const (
	// SignProviderLocal 表示使用本地 JavaScript 计算 WebSocket 签名。
	// SignProviderLocal means WebSocket signatures are generated locally with JavaScript.
	SignProviderLocal = "local"
	// SignProviderTikHub 表示使用 TikHub 在线 API 计算 WebSocket 签名。
	// SignProviderTikHub means WebSocket signatures are generated by TikHub's online API.
	SignProviderTikHub = "tikhub"
)

var (
	ErrTikHubTokenEmpty  = errors.New("tikhub token 未配置")
	ErrTikHubSignInvalid = errors.New("tikhub 签名响应无效")
)

// websocketSigner 抽象 WebSocket 签名来源。
// websocketSigner abstracts the source used to generate WebSocket signatures.
type websocketSigner interface {
	Name() string
	Sign(ctx context.Context, roomID, userUniqueID, userAgent string) (string, error)
	UpdateUserAgent(userAgent string)
}

// localWebsocketSigner 使用内置 JavaScript 计算 WebSocket 签名。
// localWebsocketSigner generates WebSocket signatures with the embedded JavaScript runtime.
type localWebsocketSigner struct{}

// newLocalWebsocketSigner 创建本地签名器。
// newLocalWebsocketSigner creates a local signature provider.
func newLocalWebsocketSigner() websocketSigner {
	return localWebsocketSigner{}
}

// Name 返回本地签名器名称。
// Name returns the local signature provider name.
func (localWebsocketSigner) Name() string {
	return SignProviderLocal
}

// Sign 使用本地 JS 生成 WebSocket 签名。
// Sign generates a WebSocket signature using the local JavaScript implementation.
// 参数/Parameters:
//   - roomID: 抖音长房间 ID。 Douyin long room ID.
//   - userUniqueID: WebSocket 签名所需的用户唯一 ID。 User unique ID required for WebSocket signing.
func (localWebsocketSigner) Sign(_ context.Context, roomID, userUniqueID, _ string) (string, error) {
	return jsScript.ExecuteJS(newWebsocketSignatureParams(roomID, userUniqueID).XMSStub()), nil
}

// UpdateUserAgent 保持接口一致，本地签名器的 UA 在 LoadGoja 时设置。
// UpdateUserAgent keeps interface parity; the local signer uses the UA loaded into Goja.
// 参数/Parameters:
//   - string: 新的 User-Agent；本地签名器忽略该值。 New User-Agent; ignored by the local signer.
func (localWebsocketSigner) UpdateUserAgent(string) {}

// tikhubWebsocketSigner 使用 TikHub 在线 API 计算 WebSocket 签名。
// tikhubWebsocketSigner generates WebSocket signatures through TikHub's online API.
type tikhubWebsocketSigner struct {
	token  string
	client *tikhub.Client
}

// newTikHubWebsocketSigner 创建 TikHub 在线签名器。
// newTikHubWebsocketSigner creates a TikHub-backed signature provider.
// 参数/Parameters:
//   - token: TikHub API Token。 TikHub API token.
//   - userAgent: 请求 TikHub 时使用的 User-Agent。 User-Agent used when calling TikHub.
func newTikHubWebsocketSigner(token, userAgent string) websocketSigner {
	token = strings.TrimSpace(token)
	return &tikhubWebsocketSigner{
		token:  token,
		client: newTikHubClient(token, userAgent),
	}
}

// Name 返回 TikHub 签名器名称。
// Name returns the TikHub signature provider name.
func (s *tikhubWebsocketSigner) Name() string {
	return SignProviderTikHub
}

// LogStatus 输出 TikHub API Key 的安全摘要，避免直接打印密钥。
// LogStatus logs a safe summary of the TikHub API key without exposing the secret.
// 参数/Parameters:
//   - logger: 输出状态日志的日志器。 Logger used to emit status.
//   - liveID: 当前直播间标识，用于日志定位。 Current live room identifier for log context.
func (s *tikhubWebsocketSigner) LogStatus(logger logSink, liveID string) {
	if logger == nil {
		return
	}
	token := strings.TrimSpace(s.token)
	if token == "" {
		logger.Warn("TikHub API Key 未配置", "live_id", liveID)
		return
	}

	hash := sha256.Sum256([]byte(token))
	logger.Info(
		"TikHub API Key 已加载",
		"live_id", liveID,
		"key_len", len(token),
		"key_mask", maskSecret(token),
		"key_sha256_8", hex.EncodeToString(hash[:])[:8],
	)
}

// UpdateUserAgent 将当前 UA 同步到 TikHub HTTP 客户端。
// UpdateUserAgent syncs the current user agent to the TikHub HTTP client.
// 参数/Parameters:
//   - userAgent: 新的浏览器 User-Agent。 New browser User-Agent.
func (s *tikhubWebsocketSigner) UpdateUserAgent(userAgent string) {
	if s.client == nil {
		s.client = newTikHubClient(s.token, userAgent)
		return
	}
	client := s.client.ReqClient()
	if client != nil {
		client.SetUserAgent(userAgent)
	}
}

// Sign 调用 TikHub API 生成 WebSocket 签名。
// Sign calls the TikHub API to generate a WebSocket signature.
// 参数/Parameters:
//   - ctx: 请求上下文。 Request context.
//   - roomID: 抖音长房间 ID。 Douyin long room ID.
//   - userUniqueID: WebSocket 签名所需的用户唯一 ID。 User unique ID required for WebSocket signing.
//   - userAgent: 当前浏览器 User-Agent。 Current browser User-Agent.
func (s *tikhubWebsocketSigner) Sign(ctx context.Context, roomID, userUniqueID, userAgent string) (string, error) {
	token := strings.TrimSpace(s.token)
	if token == "" {
		return "", ErrTikHubTokenEmpty
	}
	if roomID == "" || userUniqueID == "" {
		return "", fmt.Errorf("%w: room_id 或 user_unique_id 为空", ErrTikHubSignInvalid)
	}

	if s.client == nil {
		s.client = newTikHubClient(token, userAgent)
	}
	resp, err := s.client.DouyinWeb.GenerateWssXbSignature(ctx, tikhub.DouyinWebGenerateWssXbSignatureRequest{
		UserAgent:    userAgent,
		RoomID:       roomID,
		UserUniqueID: userUniqueID,
	})
	if err != nil {
		return "", fmt.Errorf("请求 tikhub 签名失败: %w", err)
	}
	if resp == nil {
		return "", fmt.Errorf("%w: nil response", ErrTikHubSignInvalid)
	}
	if resp.StatusCode != 0 && (resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices) {
		return "", fmt.Errorf("tikhub 签名接口返回异常 status=%d body=%s", resp.StatusCode, string(resp.Raw))
	}
	if !isTikHubSuccessCode(resp.Code) {
		return "", fmt.Errorf("tikhub 签名接口业务失败 code=%d message=%s body=%s", resp.Code, firstNonEmptyString(resp.MessageZH, resp.Message), string(resp.Raw))
	}

	signature := extractTikHubSignature(resp.Raw)
	if signature == "" && len(resp.Data) > 0 {
		signature = extractTikHubSignature(resp.Data)
	}
	if signature == "" {
		return "", fmt.Errorf("%w: body=%s", ErrTikHubSignInvalid, string(resp.Raw))
	}
	signature = normalizeTikHubSignature(signature)
	if signature == "" {
		return "", fmt.Errorf("%w: body=%s", ErrTikHubSignInvalid, string(resp.Raw))
	}
	return signature, nil
}

// isTikHubSuccessCode 判断 TikHub 业务状态码是否表示成功。
// isTikHubSuccessCode reports whether a TikHub business code indicates success.
// 参数/Parameters:
//   - code: TikHub 响应中的业务状态码。 Business status code returned by TikHub.
func isTikHubSuccessCode(code int) bool {
	return code == 0 || code == http.StatusOK
}

// maskSecret 掩码敏感值，仅保留首尾少量字符。
// maskSecret masks a secret value while keeping a small prefix and suffix.
// 参数/Parameters:
//   - value: 待掩码的敏感字符串。 Sensitive string to mask.
func maskSecret(value string) string {
	value = strings.TrimSpace(value)
	switch {
	case value == "":
		return ""
	case len(value) <= 8:
		return strings.Repeat("*", len(value))
	default:
		return value[:4] + strings.Repeat("*", len(value)-8) + value[len(value)-4:]
	}
}

// firstNonEmptyString 返回第一个去空白后非空的字符串。
// firstNonEmptyString returns the first non-empty string after trimming spaces.
// 参数/Parameters:
//   - values: 候选字符串列表。 Candidate strings.
func firstNonEmptyString(values ...string) string {
	for _, value := range values {
		if value = strings.TrimSpace(value); value != "" {
			return value
		}
	}
	return ""
}

// newTikHubClient 创建带超时和 UA 的 TikHub 客户端。
// newTikHubClient creates a TikHub client with timeout and user-agent settings.
// 参数/Parameters:
//   - token: TikHub API Token。 TikHub API token.
//   - userAgent: 请求 TikHub 时使用的 User-Agent。 User-Agent used when calling TikHub.
func newTikHubClient(token, userAgent string) *tikhub.Client {
	return tikhub.NewClient(strings.TrimSpace(token),
		tikhub.WithTimeout(httpRequestTimeout),
		tikhub.WithUserAgent(userAgent),
	)
}

// extractTikHubSignature 从 TikHub JSON 响应中提取签名。
// extractTikHubSignature extracts a signature from a TikHub JSON response.
// 参数/Parameters:
//   - body: TikHub JSON 响应字节。 TikHub JSON response bytes.
func extractTikHubSignature(body []byte) string {
	var payload interface{}
	if err := json.Unmarshal(body, &payload); err != nil {
		return ""
	}
	return strings.TrimSpace(findSignatureValue(payload, true))
}

// findSignatureValue 在未知 JSON 结构中递归查找签名字段。
// findSignatureValue recursively searches unknown JSON shapes for a signature field.
// 参数/Parameters:
//   - value: 当前 JSON 节点。 Current JSON node.
//   - allowRawString: 是否允许当前字符串节点直接作为签名。 Whether the current string node may be treated as the signature.
func findSignatureValue(value interface{}, allowRawString bool) string {
	switch v := value.(type) {
	case string:
		if allowRawString && isLikelySignature(v) {
			return v
		}
	case map[string]interface{}:
		for _, key := range []string{
			"data",
			"xb",
			"x-bogus",
			"X-Bogus",
			"x_bogus",
			"X_Bogus",
			"xBogus",
			"XBogus",
			"signature",
			"sign",
			"result",
			"value",
			"wss_signature",
		} {
			if candidate, ok := v[key]; ok {
				if signature := findSignatureValue(candidate, true); signature != "" {
					return signature
				}
			}
		}
		for _, candidate := range v {
			if signature := findSignatureValue(candidate, false); signature != "" {
				return signature
			}
		}
	case []interface{}:
		for _, candidate := range v {
			if signature := findSignatureValue(candidate, false); signature != "" {
				return signature
			}
		}
	}
	return ""
}

// isLikelySignature 粗略判断字符串是否可能是签名值。
// isLikelySignature heuristically reports whether a string looks like a signature value.
// 参数/Parameters:
//   - value: 待判断的字符串。 String to test.
func isLikelySignature(value string) bool {
	value = strings.TrimSpace(value)
	if value == "" {
		return false
	}
	lower := strings.ToLower(value)
	if strings.Contains(lower, "request successful") || strings.Contains(lower, "请求成功") {
		return false
	}
	return true
}

// normalizeTikHubSignature 规范化 TikHub 返回的签名文本。
// normalizeTikHubSignature normalizes signature text returned by TikHub.
// 参数/Parameters:
//   - value: TikHub 返回的签名、URL 或查询片段。 Signature, URL, or query fragment returned by TikHub.
func normalizeTikHubSignature(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return ""
	}

	if parsed, err := url.Parse(value); err == nil && parsed.RawQuery != "" {
		if signature := signatureFromValues(parsed.Query()); signature != "" {
			return signature
		}
	}
	if strings.Contains(value, "=") {
		queryText := strings.TrimPrefix(value, "?")
		if values, err := url.ParseQuery(queryText); err == nil {
			if signature := signatureFromValues(values); signature != "" {
				return signature
			}
		}
	}
	if strings.Contains(value, "%") {
		if decoded, err := url.PathUnescape(value); err == nil {
			return strings.TrimSpace(decoded)
		}
	}
	return value
}

// signatureFromValues 从 URL 查询参数中提取签名字段。
// signatureFromValues extracts a signature field from URL query values.
// 参数/Parameters:
//   - values: 已解析的 URL 查询参数。 Parsed URL query values.
func signatureFromValues(values url.Values) string {
	for _, key := range []string{
		"signature",
		"xb",
		"X-Bogus",
		"x-bogus",
		"x_bogus",
		"X_Bogus",
		"xBogus",
		"XBogus",
		"wss_signature",
		"sign",
		"result",
		"value",
	} {
		if value := strings.TrimSpace(values.Get(key)); value != "" {
			return value
		}
	}
	return ""
}
