package douyinLive

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
	"sync"

	tikhub "github.com/jwwsjlm/Tikhub"
	"github.com/jwwsjlm/douyinLive/v2/internal/webcastsign"
	"github.com/jwwsjlm/douyinLive/v2/jsScript"
)

const (
	// SignProviderLocal 表示优先使用本地原生 Go 计算 WebSocket 签名，必要时回退到 Goja。
	// SignProviderLocal means WebSocket signatures use native Go first and fall back to Goja when needed.
	SignProviderLocal = "local"
	// SignProviderTikHub 表示使用 TikHub 在线 API 计算 WebSocket 签名。
	// SignProviderTikHub means WebSocket signatures are generated by TikHub's online API.
	SignProviderTikHub = "tikhub"
)

var (
	// ErrLocalSignerNotPrepared indicates that the local signer has not received its session profile.
	// ErrLocalSignerNotPrepared 表示本地签名器尚未载入直播会话画像。
	ErrLocalSignerNotPrepared = errors.New("本地 WebSocket 签名器尚未初始化")
	// ErrLocalSignerClosed indicates that the local signer has already released its resources.
	// ErrLocalSignerClosed 表示本地签名器已经释放资源并关闭。
	ErrLocalSignerClosed = errors.New("本地 WebSocket 签名器已关闭")
	// ErrLocalSignerProfile indicates that the signing request does not match the prepared session profile.
	// ErrLocalSignerProfile 表示签名请求与已准备的直播会话画像不一致。
	ErrLocalSignerProfile = errors.New("本地 WebSocket 签名器画像不匹配")
	// ErrTikHubTokenEmpty indicates that TikHub signing was selected without an API token.
	// ErrTikHubTokenEmpty 表示选择 TikHub 签名时没有配置 API Token。
	ErrTikHubTokenEmpty = errors.New("tikhub token 未配置")
	// ErrTikHubSignInvalid indicates that TikHub did not return a usable WebSocket signature.
	// ErrTikHubSignInvalid 表示 TikHub 没有返回可用的 WebSocket 签名。
	ErrTikHubSignInvalid = errors.New("tikhub 签名响应无效")
)

// websocketSigner 抽象 WebSocket 签名来源。
// websocketSigner abstracts the source used to generate WebSocket signatures.
type websocketSigner interface {
	Name() string
	Sign(ctx context.Context, roomID, userUniqueID, userAgent string) (string, error)
	UpdateUserAgent(userAgent string)
}

// websocketSignerPreparer 描述需要按直播会话 UA/Cookie 初始化的签名器。
// websocketSignerPreparer describes signers initialized from a session UA/cookie profile.
type websocketSignerPreparer interface {
	Prepare(userAgent, cookie string) error
}

// websocketSignerCloser 描述持有独立运行时或网络资源的签名器。
// websocketSignerCloser describes signers that own runtime or network resources.
type websocketSignerCloser interface {
	Close()
}

// websocketSignerFallback 描述能够在原生签名握手失败后切换兼容实现的签名器。
// websocketSignerFallback describes a signer that can switch to a compatibility implementation after a native handshake failure.
type websocketSignerFallback interface {
	ActivateFallback() (bool, error)
}

// websocketSignerImplementation 描述签名器当前实际使用的底层实现。
// websocketSignerImplementation reports the concrete implementation currently used by a signer.
type websocketSignerImplementation interface {
	Implementation() string
}

// websocketSignerFingerprintUpdater 描述能够绑定会话级浏览器画像的签名器。
// websocketSignerFingerprintUpdater describes signers that can bind a session-scoped browser fingerprint.
type websocketSignerFingerprintUpdater interface {
	UpdateBrowserFingerprint(browserFingerprint)
}

// websocketSignerImplementationName 返回日志使用的底层签名实现名称。
// websocketSignerImplementationName returns the concrete signer implementation name used in logs.
func websocketSignerImplementationName(signer websocketSigner) string {
	if implementation, ok := signer.(websocketSignerImplementation); ok {
		return implementation.Implementation()
	}
	if signer == nil {
		return "unknown"
	}
	return signer.Name()
}

// localWebsocketSigner 优先使用原生 Go，并按直播会话保留可延迟启用的 Goja 兼容回退。
// localWebsocketSigner prefers native Go and keeps a lazily initialized per-session Goja compatibility fallback.
type localWebsocketSigner struct {
	mu          sync.Mutex
	fallbackMu  sync.Mutex
	native      *webcastsign.Generator
	runtime     *jsScript.Signer
	userAgent   string
	cookie      string
	profile     browserFingerprint
	useFallback bool
	closed      bool
}

// newLocalWebsocketSigner 创建本地签名器。
// newLocalWebsocketSigner creates a local signature provider.
func newLocalWebsocketSigner() websocketSigner {
	return &localWebsocketSigner{native: webcastsign.NewGenerator()}
}

// Name 返回本地签名器名称。
// Name returns the local signature provider name.
func (*localWebsocketSigner) Name() string {
	return SignProviderLocal
}

// Implementation 返回当前实际签名实现，供日志区分 native 和 goja_fallback。
// Implementation reports the active implementation for native/goja_fallback diagnostics.
func (s *localWebsocketSigner) Implementation() string {
	if s == nil {
		return "native"
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.useFallback {
		return "goja_fallback"
	}
	return "native"
}

// Prepare 绑定当前直播会话画像；仅在已进入兼容模式时初始化或刷新 Goja Runtime。
// Prepare binds the current session profile and initializes or refreshes Goja only in compatibility mode.
func (s *localWebsocketSigner) Prepare(userAgent, cookie string) error {
	if s == nil {
		return ErrLocalSignerClosed
	}

	s.fallbackMu.Lock()
	defer s.fallbackMu.Unlock()

	s.mu.Lock()
	if s.closed {
		s.mu.Unlock()
		return ErrLocalSignerClosed
	}
	if s.userAgent == userAgent && s.cookie == cookie && (!s.useFallback || s.runtime != nil && s.runtime.ProfileMatchesWithBrowserProfile(userAgent, cookie, s.profile.ID)) {
		s.mu.Unlock()
		return nil
	}
	oldRuntime := s.runtime
	s.runtime = nil
	s.userAgent = userAgent
	s.cookie = cookie
	if s.native == nil {
		s.native = webcastsign.NewGenerator()
	}
	useFallback := s.useFallback
	s.mu.Unlock()

	if oldRuntime != nil {
		oldRuntime.Close()
	}
	if !useFallback {
		return nil
	}
	return s.prepareFallback(userAgent, cookie)
}

// UpdateBrowserFingerprint 更新兼容 Runtime 使用的会话画像；已创建的 Runtime 会被丢弃并按需重建。
// UpdateBrowserFingerprint updates the session profile used by the fallback runtime and invalidates any stale runtime.
func (s *localWebsocketSigner) UpdateBrowserFingerprint(profile browserFingerprint) {
	if s == nil {
		return
	}
	s.fallbackMu.Lock()
	defer s.fallbackMu.Unlock()
	s.mu.Lock()
	if s.closed || s.profile.ID == profile.ID {
		s.mu.Unlock()
		return
	}
	oldRuntime := s.runtime
	s.runtime = nil
	s.profile = profile
	s.mu.Unlock()
	if oldRuntime != nil {
		oldRuntime.Close()
	}
}

// Sign 优先使用原生 Go 生成 WebSocket 签名，兼容模式下改用会话独享的 Goja Runtime。
// Sign prefers native Go and uses the session's isolated Goja runtime in compatibility mode.
// 参数/Parameters:
//   - roomID: 抖音长房间 ID。 Douyin long room ID.
//   - userUniqueID: WebSocket 签名所需的用户唯一 ID。 User unique ID required for WebSocket signing.
func (s *localWebsocketSigner) Sign(_ context.Context, roomID, userUniqueID, userAgent string) (string, error) {
	if s == nil {
		return "", ErrLocalSignerClosed
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed {
		return "", ErrLocalSignerClosed
	}
	if userAgent != "" && s.userAgent != userAgent {
		return "", fmt.Errorf("%w: prepared=%q current=%q", ErrLocalSignerProfile, s.userAgent, userAgent)
	}
	xMSStub := newWebsocketSignatureParams(roomID, userUniqueID).XMSStub()
	if s.useFallback {
		if s.runtime == nil {
			return "", ErrLocalSignerNotPrepared
		}
		return s.runtime.Sign(xMSStub)
	}
	if s.native == nil {
		s.native = webcastsign.NewGenerator()
	}
	return s.native.Sign(xMSStub)
}

// ActivateFallback 延迟创建当前会话的 Goja Runtime，并让后续重连继续使用兼容实现。
// ActivateFallback lazily creates the session Goja runtime and keeps subsequent reconnects on the compatibility implementation.
func (s *localWebsocketSigner) ActivateFallback() (bool, error) {
	if s == nil {
		return false, ErrLocalSignerClosed
	}
	s.fallbackMu.Lock()
	defer s.fallbackMu.Unlock()

	s.mu.Lock()
	if s.closed {
		s.mu.Unlock()
		return false, ErrLocalSignerClosed
	}
	if s.useFallback && s.runtime != nil {
		s.mu.Unlock()
		return false, nil
	}
	userAgent, cookie, profile := s.userAgent, s.cookie, s.profile
	s.mu.Unlock()

	if err := s.prepareFallbackWithProfile(userAgent, cookie, profile); err != nil {
		return false, err
	}
	return true, nil
}

// prepareFallback 为当前画像创建 Goja Runtime，并处理并发切换和关闭竞争。
// prepareFallback creates a Goja runtime for the current profile while handling concurrent switches and close races.
func (s *localWebsocketSigner) prepareFallback(userAgent, cookie string) error {
	s.mu.Lock()
	profile := s.profile
	s.mu.Unlock()
	return s.prepareFallbackWithProfile(userAgent, cookie, profile)
}

func (s *localWebsocketSigner) prepareFallbackWithProfile(userAgent, cookie string, profile browserFingerprint) error {
	if profile.ID == "" {
		profile = newBrowserFingerprint()
	}
	runtime, err := jsScript.NewSignerWithProfile(userAgent, cookie, profile.jsProfile())
	if err != nil {
		return err
	}

	s.mu.Lock()
	if s.closed {
		s.mu.Unlock()
		runtime.Close()
		return ErrLocalSignerClosed
	}
	if s.userAgent != userAgent || s.cookie != cookie || (s.profile.ID != "" && s.profile.ID != profile.ID) {
		s.mu.Unlock()
		runtime.Close()
		return ErrLocalSignerProfile
	}
	oldRuntime := s.runtime
	s.runtime = runtime
	s.useFallback = true
	s.mu.Unlock()
	if oldRuntime != nil {
		oldRuntime.Close()
	}
	return nil
}

// UpdateUserAgent 保持接口一致；本地签名器会在 Prepare 时原子绑定完整 UA/Cookie 画像。
// UpdateUserAgent keeps interface parity; Prepare atomically binds the full UA/cookie profile.
// 参数/Parameters:
//   - string: 新的 User-Agent；本地签名器忽略该值。 New User-Agent; ignored by the local signer.
func (*localWebsocketSigner) UpdateUserAgent(string) {}

// Close 释放当前直播会话的 Goja Runtime 引用。
// Close releases this live session's Goja runtime references.
func (s *localWebsocketSigner) Close() {
	if s == nil {
		return
	}
	s.mu.Lock()
	if s.closed {
		s.mu.Unlock()
		return
	}
	s.closed = true
	runtime := s.runtime
	s.runtime = nil
	s.native = nil
	s.userAgent = ""
	s.cookie = ""
	s.profile = browserFingerprint{}
	s.mu.Unlock()
	if runtime != nil {
		runtime.Close()
	}
}

// tikhubWebsocketSigner 使用 TikHub 在线 API 计算 WebSocket 签名。
// tikhubWebsocketSigner generates WebSocket signatures through TikHub's online API.
type tikhubWebsocketSigner struct {
	token  string
	client *tikhub.Client
}

// newTikHubWebsocketSigner 创建 TikHub 在线签名器。
// newTikHubWebsocketSigner creates a TikHub-backed signature provider.
// 参数/Parameters:
//   - token: TikHub API Token。 TikHub API token.
//   - userAgent: 请求 TikHub 时使用的 User-Agent。 User-Agent used when calling TikHub.
func newTikHubWebsocketSigner(token, userAgent string) websocketSigner {
	token = strings.TrimSpace(token)
	return &tikhubWebsocketSigner{
		token:  token,
		client: newTikHubClient(token, userAgent),
	}
}

// Name 返回 TikHub 签名器名称。
// Name returns the TikHub signature provider name.
func (s *tikhubWebsocketSigner) Name() string {
	return SignProviderTikHub
}

// LogStatus 输出 TikHub API Key 的安全摘要，避免直接打印密钥。
// LogStatus logs a safe summary of the TikHub API key without exposing the secret.
// 参数/Parameters:
//   - logger: 输出状态日志的日志器。 Logger used to emit status.
//   - liveID: 当前直播间标识，用于日志定位。 Current live room identifier for log context.
func (s *tikhubWebsocketSigner) LogStatus(logger logSink, liveID string) {
	if logger == nil {
		return
	}
	token := strings.TrimSpace(s.token)
	if token == "" {
		logger.Warn("TikHub API Key 未配置", "live_id", liveID)
		return
	}

	hash := sha256.Sum256([]byte(token))
	logger.Info(
		"TikHub API Key 已加载",
		"live_id", liveID,
		"key_len", len(token),
		"key_mask", maskSecret(token),
		"key_sha256_8", hex.EncodeToString(hash[:])[:8],
	)
}

// UpdateUserAgent 将当前 UA 同步到 TikHub HTTP 客户端。
// UpdateUserAgent syncs the current user agent to the TikHub HTTP client.
// 参数/Parameters:
//   - userAgent: 新的浏览器 User-Agent。 New browser User-Agent.
func (s *tikhubWebsocketSigner) UpdateUserAgent(userAgent string) {
	if s.client == nil {
		s.client = newTikHubClient(s.token, userAgent)
		return
	}
	client := s.client.ReqClient()
	if client != nil {
		client.SetUserAgent(userAgent)
	}
}

// Sign 调用 TikHub API 生成 WebSocket 签名。
// Sign calls the TikHub API to generate a WebSocket signature.
// 参数/Parameters:
//   - ctx: 请求上下文。 Request context.
//   - roomID: 抖音长房间 ID。 Douyin long room ID.
//   - userUniqueID: WebSocket 签名所需的用户唯一 ID。 User unique ID required for WebSocket signing.
//   - userAgent: 当前浏览器 User-Agent。 Current browser User-Agent.
func (s *tikhubWebsocketSigner) Sign(ctx context.Context, roomID, userUniqueID, userAgent string) (string, error) {
	token := strings.TrimSpace(s.token)
	if token == "" {
		return "", ErrTikHubTokenEmpty
	}
	if roomID == "" || userUniqueID == "" {
		return "", fmt.Errorf("%w: room_id 或 user_unique_id 为空", ErrTikHubSignInvalid)
	}

	if s.client == nil {
		s.client = newTikHubClient(token, userAgent)
	}
	resp, err := s.client.DouyinWeb.GenerateWssXbSignature(ctx, tikhub.DouyinWebGenerateWssXbSignatureRequest{
		UserAgent:    userAgent,
		RoomID:       roomID,
		UserUniqueID: userUniqueID,
	})
	if err != nil {
		return "", fmt.Errorf("请求 tikhub 签名失败: %w", err)
	}
	if resp == nil {
		return "", fmt.Errorf("%w: nil response", ErrTikHubSignInvalid)
	}
	if resp.StatusCode != 0 && (resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices) {
		return "", fmt.Errorf("tikhub 签名接口返回异常 status=%d", resp.StatusCode)
	}
	if !isTikHubSuccessCode(resp.Code) {
		return "", fmt.Errorf("tikhub 签名接口业务失败 code=%d message=%s", resp.Code, firstNonEmptyString(resp.MessageZH, resp.Message))
	}

	signature := extractTikHubSignature(resp.Raw)
	if signature == "" && len(resp.Data) > 0 {
		signature = extractTikHubSignature(resp.Data)
	}
	if signature == "" {
		return "", fmt.Errorf("%w: response_len=%d", ErrTikHubSignInvalid, len(resp.Raw))
	}
	signature = normalizeTikHubSignature(signature)
	if signature == "" {
		return "", fmt.Errorf("%w: normalized response_len=%d", ErrTikHubSignInvalid, len(resp.Raw))
	}
	return signature, nil
}

// isTikHubSuccessCode 判断 TikHub 业务状态码是否表示成功。
// isTikHubSuccessCode reports whether a TikHub business code indicates success.
// 参数/Parameters:
//   - code: TikHub 响应中的业务状态码。 Business status code returned by TikHub.
func isTikHubSuccessCode(code int) bool {
	return code == 0 || code == http.StatusOK
}

// maskSecret 掩码敏感值，仅保留首尾少量字符。
// maskSecret masks a secret value while keeping a small prefix and suffix.
// 参数/Parameters:
//   - value: 待掩码的敏感字符串。 Sensitive string to mask.
func maskSecret(value string) string {
	value = strings.TrimSpace(value)
	switch {
	case value == "":
		return ""
	case len(value) <= 8:
		return strings.Repeat("*", len(value))
	default:
		return value[:4] + strings.Repeat("*", len(value)-8) + value[len(value)-4:]
	}
}

// firstNonEmptyString 返回第一个去空白后非空的字符串。
// firstNonEmptyString returns the first non-empty string after trimming spaces.
// 参数/Parameters:
//   - values: 候选字符串列表。 Candidate strings.
func firstNonEmptyString(values ...string) string {
	for _, value := range values {
		if value = strings.TrimSpace(value); value != "" {
			return value
		}
	}
	return ""
}

// newTikHubClient 创建带超时和 UA 的 TikHub 客户端。
// newTikHubClient creates a TikHub client with timeout and user-agent settings.
// 参数/Parameters:
//   - token: TikHub API Token。 TikHub API token.
//   - userAgent: 请求 TikHub 时使用的 User-Agent。 User-Agent used when calling TikHub.
func newTikHubClient(token, userAgent string) *tikhub.Client {
	return tikhub.NewClient(strings.TrimSpace(token),
		tikhub.WithTimeout(httpRequestTimeout),
		tikhub.WithUserAgent(userAgent),
	)
}

// extractTikHubSignature 从 TikHub JSON 响应中提取签名。
// extractTikHubSignature extracts a signature from a TikHub JSON response.
// 参数/Parameters:
//   - body: TikHub JSON 响应字节。 TikHub JSON response bytes.
func extractTikHubSignature(body []byte) string {
	var payload interface{}
	if err := json.Unmarshal(body, &payload); err != nil {
		return ""
	}
	return strings.TrimSpace(findSignatureValue(payload, true))
}

// findSignatureValue 在未知 JSON 结构中递归查找签名字段。
// findSignatureValue recursively searches unknown JSON shapes for a signature field.
// 参数/Parameters:
//   - value: 当前 JSON 节点。 Current JSON node.
//   - allowRawString: 是否允许当前字符串节点直接作为签名。 Whether the current string node may be treated as the signature.
func findSignatureValue(value interface{}, allowRawString bool) string {
	switch v := value.(type) {
	case string:
		if allowRawString && isLikelySignature(v) {
			return v
		}
	case map[string]interface{}:
		for _, key := range []string{
			"data",
			"xb",
			"x-bogus",
			"X-Bogus",
			"x_bogus",
			"X_Bogus",
			"xBogus",
			"XBogus",
			"signature",
			"sign",
			"result",
			"value",
			"wss_signature",
		} {
			if candidate, ok := v[key]; ok {
				if signature := findSignatureValue(candidate, true); signature != "" {
					return signature
				}
			}
		}
		for _, candidate := range v {
			if signature := findSignatureValue(candidate, false); signature != "" {
				return signature
			}
		}
	case []interface{}:
		for _, candidate := range v {
			if signature := findSignatureValue(candidate, false); signature != "" {
				return signature
			}
		}
	}
	return ""
}

// isLikelySignature 粗略判断字符串是否可能是签名值。
// isLikelySignature heuristically reports whether a string looks like a signature value.
// 参数/Parameters:
//   - value: 待判断的字符串。 String to test.
func isLikelySignature(value string) bool {
	value = strings.TrimSpace(value)
	if value == "" {
		return false
	}
	lower := strings.ToLower(value)
	if strings.Contains(lower, "request successful") || strings.Contains(lower, "请求成功") {
		return false
	}
	return true
}

// normalizeTikHubSignature 规范化 TikHub 返回的签名文本。
// normalizeTikHubSignature normalizes signature text returned by TikHub.
// 参数/Parameters:
//   - value: TikHub 返回的签名、URL 或查询片段。 Signature, URL, or query fragment returned by TikHub.
func normalizeTikHubSignature(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return ""
	}

	if parsed, err := url.Parse(value); err == nil && parsed.RawQuery != "" {
		if signature := signatureFromValues(parsed.Query()); signature != "" {
			return signature
		}
	}
	if strings.Contains(value, "=") {
		queryText := strings.TrimPrefix(value, "?")
		if values, err := url.ParseQuery(queryText); err == nil {
			if signature := signatureFromValues(values); signature != "" {
				return signature
			}
		}
	}
	if strings.Contains(value, "%") {
		if decoded, err := url.PathUnescape(value); err == nil {
			return strings.TrimSpace(decoded)
		}
	}
	return value
}

// signatureFromValues 从 URL 查询参数中提取签名字段。
// signatureFromValues extracts a signature field from URL query values.
// 参数/Parameters:
//   - values: 已解析的 URL 查询参数。 Parsed URL query values.
func signatureFromValues(values url.Values) string {
	for _, key := range []string{
		"signature",
		"xb",
		"X-Bogus",
		"x-bogus",
		"x_bogus",
		"X_Bogus",
		"xBogus",
		"XBogus",
		"wss_signature",
		"sign",
		"result",
		"value",
	} {
		if value := strings.TrimSpace(values.Get(key)); value != "" {
			return value
		}
	}
	return ""
}
